name: Magento 2 Standards

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  magento-coding-standard:
    name: M2 Coding Standard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: extdn/github-actions-m2/magento-coding-standard/8.1@master
        with:
          phpcs_severity: 8
          phpcs_report: full
